import type { Metadata } from "next";


type Props = {
  children: React.ReactNode;
  
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Props) {

  return (
         children
  );
}
